vim:
  embed_dim: 256
  depth: 8
  expand_ratio: 3
  d_state: 32
  kernel_size: 4

  img_size: 128
  patch_size: 32
  in_chans: 1
  num_classes: 600

#  directions: [ [ 'h', 'h_flip' ], [ 'v', 'v_flip' ], [ 'h', 'h_flip' ], [ 'v', 'v_flip' ], [ 'h', 'h_flip' ], [ 'v', 'v_flip' ], [ 'h', 'h_flip' ], [ 'v', 'v_flip' ]]
  directions: null
  drop_rate: 0.1
  drop_path_rate: 0.2


super_vim:
  embed_dim: 256
  depth: 6
  expand_ratio: 3
  d_state: 64
  kernel_size: 4

  img_size: 128
  patch_size: 32
  in_chans: 1
  num_classes: 600

  directions: null
  drop_rate: 0.1
  drop_path_rate: 0.2

search_space:
  embed_dim:
    - 128
    - 192
    - 256
  depth:
    - 4
    - 6
  expand_ratio:
    - 1
    - 2
    - 3
  d_state:
    - 32
    - 64
  kernel_size:
    - 2
    - 4
  direction:
    - ['h']
    - ['h_flip']
    - ['v']
    - ['v_flip']